name: "Build, Test and Pack"

on:
  push:
    branches: [ master ]
    # Trigger on release tags
    tags: [ 'v[0-9]+*' ]
  pull_request:
    branches: [ master ]
jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}

  build-and-test:
    name: "Build and Test"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build and Pack
      run: dotnet build --configuration Release

    - name: Test (Framework 4.6.1)
      run: dotnet test --configuration Release --no-build output\Release\net461\*Tests.dll -- NUnit.TestOutputXml=TestResults
      if: matrix.os != 'ubuntu-latest'

    - name: Test (Framework and .NET latest)
      run: dotnet test --configuration Release --no-build -- NUnit.TestOutputXml=TestResults
      if: matrix.os != 'ubuntu-latest'

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Results (${{matrix.os}})
        path: "**/TestResults/*.xml"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: l10nsharp-nugetpackage
        path: |
          output/*.nupkg
          output/*.snupkg
      if: matrix.os == 'ubuntu-latest'

  publish-nuget:
    name: "Publish NuGet package"
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Publish to Nuget
      run: dotnet nuget push artifacts/**/*.*nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.SILLSDEV_PUBLISH_NUGET_ORG}} --skip-duplicate
